version: "3"

services:
  firefox:
    image: selenium/node-firefox:3.141.59-zirconium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  selenium-hub:
    image: selenium/hub:3.141.59-zirconium
    container_name: selenium-hub
    ports:
      - 4444:4444

  data:
    image: mongo:3.6
    container_name: data
    ports:
      - 27017:27017

  app:
    build: .
    command: sh -c "java -jar ./app/target/*.jar"
    container_name: app
    environment:
      - SPRING_PROFILES_ACTIVE=container
    ports:
      - 8080:8080
    links:
      - data
      - firefox
