version: "3"

services:
  data:
    image: mongo:3.6
    container_name: data
    ports:
      - 27017:27017

  app:
    build: .
    command: sh -c "java -jar ./app/target/*.jar"
    container_name: app
    environment:
      - SPRING_PROFILES_ACTIVE=container
    ports:
      - 8080:8080
    links:
      - data
