spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

server:
  port: ${PORT:8080}

---
spring:
  profiles: container
  data:
    mongodb:
      database: property-report
      host: data
      port: 27017

---
spring:
  profiles: default
  data:
    mongodb:
      host: localhost
      port: 27017

---
spring:
  profiles: prod
  data:
    mongodb:
      uri: ${MONGODB_URI}
