server:
  port: ${PORT:8080}

---
spring:
  profiles: container
  data:
    mongodb:
      database: property-report
      host: data
      port: 27017

---
spring:
  profiles: default
  data:
    mongodb:
      host: localhost
      port: 27017

---
spring:
  profiles: prod
  data:
    mongodb:
      uri: ${MONGODB_URI}
